<header>
    <nav><div class="menu-btn">
            <div class="btn-line"></div>
            <div class="btn-line"></div>
            <div class="btn-line"></div>
        </div>
        <nav class="menu">
            <div class="menu-branding">
                <div class="portrait"><img src="/img/WebPagePic.jpg" /></div>
            </div>
            <ul class="menu-nav">
                <?php
                $currentPage = basename($_SERVER['SCRIPT_FILENAME']);
                foreach ($menuitems as $url => $label):
                    $active = ($currentPage == basename($url)) ? ' id="here"' : '';
                    ?>
                    <li class="nav-item">
                        <a href="<?= $url ?>" class="nav-link"<?= $active ?>><?= $label ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
</header>