<?php
require_once __DIR__ . '/../config/variables.php';
$variablesFile = __DIR__ . '/../config/variables_' . $content . '.php';
if (file_exists($variablesFile)) {
    require_once $variablesFile;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require_once __DIR__.'/../template/head.phtml'; ?>
</head>
<body>
<?php require_once __DIR__.'/../template/menu.phtml'; ?>
<main id="<?php echo $content; ?>">
    <?php
    $contentFile = __DIR__ . '/../template/content/' . basename($content, '.php') . '.phtml';
    if (file_exists($contentFile)) {
        require_once $contentFile;
    } else {
        echo "Page content not found.";
    }
    ?>
</main>
<?php require_once __DIR__.'/../template/footer.phtml'; ?>
</body>
</html>
