<h1 class="lg-heading">
    <?= $contact ?> <span class="text-secondary"><?=$me?> </span>
</h1>
<h2 id="sm-heading">
    <?= $reachme ?>
</h2>
<div class="boxes">
    <div>
        <span class="text-secondary"><?=$email?></span><?=$emailmain?>
    </div>
    <div>
        <span class="text-secondary"><?=$phone?></span><?=$phonemain?>
    </div>
    <div>
        <span class="text-secondary"><?=$address?></span> <?=$addressct?>
    </div>
</div>