<h1 class="lg-heading">
    <?= $my ?> <span class="text-secondary"><?= $work ?></span></h1>
<h2 id="sm-heading">
    <?= $checkMyProjects ?>
</h2>
<div class="projects">
    <?php foreach ($projects as $project) : ?>
        <div class="item">
            <a href="#!">
                <img src="<?= $project['img'] ?>" class="project-img" alt="Project Pic" id="project">
            </a>
            <a href="#" class="btn-light">
                 <i class="fas fa-eye"></i><?= $project['project'] ?>
            </a>
            <a href="<?=$project['github']?>" class="btn-dark">
                <i class="fab fa-github"></i>
            </a>
        </div>
    <?php endforeach; ?>
</div>
